"""改变数据长度

Revision ID: e9269bad83a8
Revises: 9127d0fed8a3
Create Date: 2025-07-12 15:19:09.066699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e9269bad83a8'
down_revision: Union[str, None] = '9127d0fed8a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_car')
    op.drop_table('t_clazz')
    op.drop_table('t_student')
    op.drop_table('servlet_dept')
    op.drop_table('t_user')
    op.drop_table('t_stu')
    op.drop_table('dept')
    op.drop_index(op.f('ix_sample_table_Respondent'), table_name='sample_table')
    op.drop_table('sample_table')
    op.drop_index(op.f('id_UNIQUE'), table_name='account')
    op.drop_table('account')
    op.drop_table('spring_user')
    op.drop_table('salgrade')
    op.drop_table('py_sql')
    op.drop_index(op.f('id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_table('spring_bank')
    op.drop_index(op.f('id_UNIQUE'), table_name='py_products')
    op.drop_table('py_products')
    op.drop_table('t_role')
    op.drop_table('emp')
    op.alter_column('tickets2', 'creator',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('tickets2', 'assignee',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('tickets2', 'source',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=111),
               existing_nullable=True)
    op.alter_column('tickets2', 'reporter',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('tickets2', 'org_1',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('tickets2', 'org_2',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets2', 'org_2',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('tickets2', 'org_1',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('tickets2', 'reporter',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('tickets2', 'source',
               existing_type=sa.String(length=111),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('tickets2', 'assignee',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('tickets2', 'creator',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.create_table('emp',
    sa.Column('EMPNO', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ENAME', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('JOB', mysql.VARCHAR(length=9), nullable=True),
    sa.Column('MGR', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('HIREDATE', sa.DATE(), nullable=True),
    sa.Column('SAL', mysql.DOUBLE(precision=7, scale=2, asdecimal=True), nullable=True),
    sa.Column('COMM', mysql.DOUBLE(precision=7, scale=2, asdecimal=True), nullable=True),
    sa.Column('DEPTNO', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('EMPNO'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('t_role',
    sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('py_products',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('price', mysql.FLOAT(), nullable=False),
    sa.Column('from', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('class', mysql.VARCHAR(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('id_UNIQUE'), 'py_products', ['id'], unique=True)
    op.create_table('spring_bank',
    sa.Column('actno', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('balance', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.PrimaryKeyConstraint('actno'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tickets',
    sa.Column('id', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('creator', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('assignee', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('urgency', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('impact', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('priority', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('source', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('reporter', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('jira_link', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('org_1', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('org_2', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('org_3', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('event_type_1', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('event_type_2', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('event_type_3', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('event_type_4', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('reported_at', mysql.DATETIME(), nullable=True),
    sa.Column('completed_at', mysql.DATETIME(), nullable=True),
    sa.Column('completed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('escalated', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('lead_time', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('id'), 'tickets', ['id'], unique=True)
    op.create_table('py_sql',
    sa.Column('date', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('order_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('money', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('province', mysql.VARCHAR(length=45), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('salgrade',
    sa.Column('GRADE', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('LOSAL', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('HISAL', mysql.INTEGER(), autoincrement=False, nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('spring_user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('real_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('age', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('account',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('actno', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('balance', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('id_UNIQUE'), 'account', ['id'], unique=True)
    op.create_table('sample_table',
    sa.Column('Respondent', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('MainBranch', mysql.TEXT(), nullable=True),
    sa.Column('Hobbyist', mysql.TEXT(), nullable=True),
    sa.Column('OpenSourcer', mysql.TEXT(), nullable=True),
    sa.Column('OpenSource', mysql.TEXT(), nullable=True),
    sa.Column('Employment', mysql.TEXT(), nullable=True),
    sa.Column('Country', mysql.TEXT(), nullable=True),
    sa.Column('Student', mysql.TEXT(), nullable=True),
    sa.Column('EdLevel', mysql.TEXT(), nullable=True),
    sa.Column('UndergradMajor', mysql.TEXT(), nullable=True),
    sa.Column('EduOther', mysql.TEXT(), nullable=True),
    sa.Column('OrgSize', mysql.TEXT(), nullable=True),
    sa.Column('DevType', mysql.TEXT(), nullable=True),
    sa.Column('YearsCode', mysql.TEXT(), nullable=True),
    sa.Column('Age1stCode', mysql.TEXT(), nullable=True),
    sa.Column('YearsCodePro', mysql.TEXT(), nullable=True),
    sa.Column('CareerSat', mysql.TEXT(), nullable=True),
    sa.Column('JobSat', mysql.TEXT(), nullable=True),
    sa.Column('MgrIdiot', mysql.TEXT(), nullable=True),
    sa.Column('MgrMoney', mysql.TEXT(), nullable=True),
    sa.Column('MgrWant', mysql.TEXT(), nullable=True),
    sa.Column('JobSeek', mysql.TEXT(), nullable=True),
    sa.Column('LastHireDate', mysql.TEXT(), nullable=True),
    sa.Column('LastInt', mysql.TEXT(), nullable=True),
    sa.Column('FizzBuzz', mysql.TEXT(), nullable=True),
    sa.Column('JobFactors', mysql.TEXT(), nullable=True),
    sa.Column('ResumeUpdate', mysql.TEXT(), nullable=True),
    sa.Column('CurrencySymbol', mysql.TEXT(), nullable=True),
    sa.Column('CurrencyDesc', mysql.TEXT(), nullable=True),
    sa.Column('CompTotal', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('CompFreq', mysql.TEXT(), nullable=True),
    sa.Column('ConvertedComp', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('WorkWeekHrs', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('WorkPlan', mysql.TEXT(), nullable=True),
    sa.Column('WorkChallenge', mysql.TEXT(), nullable=True),
    sa.Column('WorkRemote', mysql.TEXT(), nullable=True),
    sa.Column('WorkLoc', mysql.TEXT(), nullable=True),
    sa.Column('ImpSyn', mysql.TEXT(), nullable=True),
    sa.Column('CodeRev', mysql.TEXT(), nullable=True),
    sa.Column('CodeRevHrs', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('UnitTests', mysql.TEXT(), nullable=True),
    sa.Column('PurchaseHow', mysql.TEXT(), nullable=True),
    sa.Column('PurchaseWhat', mysql.TEXT(), nullable=True),
    sa.Column('LanguageWorkedWith', mysql.TEXT(), nullable=True),
    sa.Column('LanguageDesireNextYear', mysql.TEXT(), nullable=True),
    sa.Column('DatabaseWorkedWith', mysql.TEXT(), nullable=True),
    sa.Column('DatabaseDesireNextYear', mysql.TEXT(), nullable=True),
    sa.Column('PlatformWorkedWith', mysql.TEXT(), nullable=True),
    sa.Column('PlatformDesireNextYear', mysql.TEXT(), nullable=True),
    sa.Column('WebFrameWorkedWith', mysql.TEXT(), nullable=True),
    sa.Column('WebFrameDesireNextYear', mysql.TEXT(), nullable=True),
    sa.Column('MiscTechWorkedWith', mysql.TEXT(), nullable=True),
    sa.Column('MiscTechDesireNextYear', mysql.TEXT(), nullable=True),
    sa.Column('DevEnviron', mysql.TEXT(), nullable=True),
    sa.Column('OpSys', mysql.TEXT(), nullable=True),
    sa.Column('Containers', mysql.TEXT(), nullable=True),
    sa.Column('BlockchainOrg', mysql.TEXT(), nullable=True),
    sa.Column('BlockchainIs', mysql.TEXT(), nullable=True),
    sa.Column('BetterLife', mysql.TEXT(), nullable=True),
    sa.Column('ITperson', mysql.TEXT(), nullable=True),
    sa.Column('OffOn', mysql.TEXT(), nullable=True),
    sa.Column('SocialMedia', mysql.TEXT(), nullable=True),
    sa.Column('Extraversion', mysql.TEXT(), nullable=True),
    sa.Column('ScreenName', mysql.TEXT(), nullable=True),
    sa.Column('SOVisit1st', mysql.TEXT(), nullable=True),
    sa.Column('SOVisitFreq', mysql.TEXT(), nullable=True),
    sa.Column('SOVisitTo', mysql.TEXT(), nullable=True),
    sa.Column('SOFindAnswer', mysql.TEXT(), nullable=True),
    sa.Column('SOTimeSaved', mysql.TEXT(), nullable=True),
    sa.Column('SOHowMuchTime', mysql.TEXT(), nullable=True),
    sa.Column('SOAccount', mysql.TEXT(), nullable=True),
    sa.Column('SOPartFreq', mysql.TEXT(), nullable=True),
    sa.Column('SOJobs', mysql.TEXT(), nullable=True),
    sa.Column('EntTeams', mysql.TEXT(), nullable=True),
    sa.Column('SOComm', mysql.TEXT(), nullable=True),
    sa.Column('WelcomeChange', mysql.TEXT(), nullable=True),
    sa.Column('SONewContent', mysql.TEXT(), nullable=True),
    sa.Column('Age', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('Gender', mysql.TEXT(), nullable=True),
    sa.Column('Trans', mysql.TEXT(), nullable=True),
    sa.Column('Sexuality', mysql.TEXT(), nullable=True),
    sa.Column('Ethnicity', mysql.TEXT(), nullable=True),
    sa.Column('Dependents', mysql.TEXT(), nullable=True),
    sa.Column('SurveyLength', mysql.TEXT(), nullable=True),
    sa.Column('SurveyEase', mysql.TEXT(), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_sample_table_Respondent'), 'sample_table', ['Respondent'], unique=False)
    op.create_table('dept',
    sa.Column('DEPTNO', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('DNAME', mysql.VARCHAR(length=14), nullable=True),
    sa.Column('LOC', mysql.VARCHAR(length=13), nullable=True),
    sa.PrimaryKeyConstraint('DEPTNO'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('t_stu',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('age', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('t_user',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_general_ci', length=100), nullable=False),
    sa.Column('age', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_general_ci', length=60), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('servlet_dept',
    sa.Column('deptno', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dname', mysql.VARCHAR(length=105), nullable=True),
    sa.Column('loc', mysql.VARCHAR(length=105), nullable=True),
    sa.PrimaryKeyConstraint('deptno'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('t_student',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('age', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('height', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('birth', sa.DATE(), nullable=True),
    sa.Column('gender', mysql.CHAR(length=1), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('t_clazz',
    sa.Column('cid', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cname', mysql.VARCHAR(length=45), nullable=True),
    sa.PrimaryKeyConstraint('cid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('t_car',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('car_num', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('brand', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('guide_price', mysql.DECIMAL(precision=10, scale=0), server_default=sa.text("'123'"), nullable=True),
    sa.Column('produce_time', mysql.CHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('car_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
